version: '2'
services: 
  mongo:
    extends:
      file: ./databases/mongo.yml
      service: mongo
    container_name: ${APP_NAME}-mongo
  mysql:
    extends:
      file: ./databases/mysql.yml
      service: mysql
    container_name: ${APP_NAME}-mysql
  redis:
    image: redis:5.0
    container_name: ${APP_NAME}-redis
    ports:
      - ${REDIS_PORT}:6379
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: "${APP_NAME}-mysql"
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
  mongo-express:
    image: mongo-express
    container_name: "${APP_NAME}-mongo-express"
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 2778:8081
