version: '2'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./../storage/mongo:/data/db
      - ${APP_PATH}/php-docker-boilerplate/share:/var/share
    ports:
      - ${MONGO_PORT}:27017
